# Generated by Django 4.1.7 on 2023-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3)),
                ('upfront_commission_rate', models.FloatField()),
                ('trial_commission_rate', models.FloatField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lender',
                'verbose_name_plural': 'Lenders',
            },
        ),
    ]
